plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'maven-publish'
}

/* Uncomment for local publishing */

/*apply from: 'publishLocal.gradle'*/

android {
    compileSdk 36

    defaultConfig {
        minSdk 23
        //noinspection OldTargetApi
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
    // Comment the publishing block for local maven publishing
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

    namespace 'ae.network.nicardmanagementsdk'
    buildFeatures {
        buildConfig true
        dataBinding = false  // DISABLE DataBinding
        viewBinding = true   // ENABLE ViewBinding
    }
}

dependencies {
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.10.0"
    implementation "androidx.core:core-ktx:1.17.0"

    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    implementation "com.google.android.material:material:1.13.0"

    // Retrofit2
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    // okhttp3
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'

    // BouncyCastle - SelfSignedCertificate
    implementation 'org.bouncycastle:bcpkix-jdk15to18:1.83'
}


publishing {
    publications {
        // Creates a Maven publication called "release".
        release(MavenPublication) {
            groupId = 'com.github.network-international'
            artifactId = 'card-management-sdk-android'
            version = '2.2.1'
            afterEvaluate {
                from components.release
            }
        }
    }
}